"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.apiRouter = void 0;
var express_1 = require("express");
var health_js_1 = require("./health.js");
var kiosk_js_1 = require("./kiosk.js");
var poll_js_1 = require("./poll.js");
var posts_js_1 = require("./posts.js");
var results_js_1 = require("./results.js");
var votes_js_1 = require("./votes.js");
exports.apiRouter = (0, express_1.Router)();
exports.apiRouter.use('/health', health_js_1.healthRouter);
exports.apiRouter.use('/posts', posts_js_1.postsRouter);
exports.apiRouter.use('/votes', votes_js_1.votesRouter);
exports.apiRouter.use('/results', results_js_1.resultsRouter);
exports.apiRouter.use('/poll', poll_js_1.pollRouter);
exports.apiRouter.use('/kiosk', kiosk_js_1.kioskRouter);
