import request from 'supertest';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { OfficerCode, PollState } from '../types/election.js';

// A regression test for a real incident: a code generated by "Generate
// School Codes" (electionType 'school', no house) was accepted while House
// Elections were active -- the server had no way to tell "no house on this
// code" apart from "this code works for any house", so it fell into a
// manual house-picker flow and let the officer open a House ballot with a
// School-only code. See routes/kiosk.ts activate and OfficerCode.electionType.

const mockedDataStore = {
  findOfficerCode: vi.fn<[string], OfficerCode | undefined>(),
  getPollState: vi.fn<[], PollState>(),
  countVotesByOfficerCode: vi.fn<[string], number>(),
  closeOfficerCode: vi.fn(),
  markOfficerCodeReady: vi.fn()
};

vi.mock('../storage/datastore.js', () => ({
  dataStore: mockedDataStore
}));

describe('POST /api/kiosk/activate', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockedDataStore.countVotesByOfficerCode.mockReturnValue(0);
  });

  // Duty colours: a teacher typing their code before voting opens is how
  // the admin sees they received it (green).
  it('marks a correct code ready even before voting opens, and tells the teacher so', async () => {
    mockedDataStore.findOfficerCode.mockReturnValue({ code: 'ABC123', officerName: 'Jane', electionType: 'school', createdAt: Date.now() });
    mockedDataStore.getPollState.mockReturnValue({ activeElectionType: 'school', settings: { isOpen: false, allowRevote: false } });

    const { createApp } = await import('../app.js');
    const response = await request(createApp()).post('/api/kiosk/activate').send({ secret: 'abc123' });

    expect(response.status).toBe(403);
    expect(response.body.code).toBe('READY_POLL_NOT_OPEN');
    expect(response.body.error).toContain('marked as ready');
    expect(mockedDataStore.markOfficerCodeReady).toHaveBeenCalledWith('ABC123');
  });

  it('does not mark a closed ("duty over") or unallotted code as ready', async () => {
    mockedDataStore.getPollState.mockReturnValue({ activeElectionType: 'school', settings: { isOpen: true, allowRevote: false } });
    const { createApp } = await import('../app.js');

    mockedDataStore.findOfficerCode.mockReturnValue({ code: 'ABC123', officerName: 'Jane', electionType: 'school', createdAt: 1, closedAt: 2 });
    const closed = await request(createApp()).post('/api/kiosk/activate').send({ secret: 'abc123' });
    mockedDataStore.findOfficerCode.mockReturnValue({ code: 'ABC123', officerName: '', electionType: 'school', createdAt: 1 });
    const unallotted = await request(createApp()).post('/api/kiosk/activate').send({ secret: 'abc123' });

    expect(closed.status).toBe(403);
    expect(closed.body.error).toContain('duty for it is over');
    expect(unallotted.status).toBe(403);
    expect(mockedDataStore.markOfficerCodeReady).not.toHaveBeenCalled();
  });

  it('rejects a code whose booth was ordered to re-poll, saying why', async () => {
    mockedDataStore.findOfficerCode.mockReturnValue({
      code: 'ABC123',
      officerName: 'Jane',
      electionType: 'school',
      createdAt: Date.now(),
      closedAt: Date.now(),
      repoll: { orderedAt: Date.now(), orderedBy: 'Admin', reason: 'disruption', note: '', cancelledVoteCount: 5, replacementCode: 'new999' }
    });
    mockedDataStore.getPollState.mockReturnValue({ activeElectionType: 'school', settings: { isOpen: true, allowRevote: false } });

    const { createApp } = await import('../app.js');
    const response = await request(createApp()).post('/api/kiosk/activate').send({ secret: 'abc123' });

    expect(response.status).toBe(403);
    expect(response.body.error).toContain('re-poll');
    // The new code is only given to the officer through the administrator.
    expect(response.body.error).not.toContain('new999');
  });

  it('rejects a School Elections code outright while House Elections are active', async () => {
    const schoolCode: OfficerCode = {
      code: 'ABC123',
      officerName: 'Jane',
      electionType: 'school',
      createdAt: Date.now()
    };
    mockedDataStore.findOfficerCode.mockReturnValue(schoolCode);
    mockedDataStore.getPollState.mockReturnValue({
      activeElectionType: 'house',
      settings: { isOpen: true, allowRevote: false }
    });

    const { createApp } = await import('../app.js');
    const response = await request(createApp()).post('/api/kiosk/activate').send({ secret: 'abc123' });

    expect(response.status).toBe(403);
    expect(response.body.error).toContain('School Elections');
    expect(response.body.error).toContain('cannot be used while House Elections are active');
  });

  it('rejects a House Elections code outright while School Elections are active', async () => {
    const houseCode: OfficerCode = {
      code: 'DEF456',
      officerName: 'Sam',
      electionType: 'house',
      house: 'Anand',
      createdAt: Date.now()
    };
    mockedDataStore.findOfficerCode.mockReturnValue(houseCode);
    mockedDataStore.getPollState.mockReturnValue({
      activeElectionType: 'school',
      settings: { isOpen: true, allowRevote: false }
    });

    const { createApp } = await import('../app.js');
    const response = await request(createApp()).post('/api/kiosk/activate').send({ secret: 'def456' });

    expect(response.status).toBe(403);
    expect(response.body.error).toContain('House Elections');
    expect(response.body.error).toContain('cannot be used while School Elections are active');
  });

  it('accepts a House Elections code and resolves its bound house, ignoring any client-sent house', async () => {
    const houseCode: OfficerCode = {
      code: 'DEF456',
      officerName: 'Sam',
      electionType: 'house',
      house: 'Anand',
      createdAt: Date.now()
    };
    mockedDataStore.findOfficerCode.mockReturnValue(houseCode);
    mockedDataStore.getPollState.mockReturnValue({
      activeElectionType: 'house',
      settings: { isOpen: true, allowRevote: false }
    });

    const { createApp } = await import('../app.js');
    // Even if a client tried to send a different house, the server must
    // ignore it and use the one bound to the code.
    const response = await request(createApp())
      .post('/api/kiosk/activate')
      .send({ secret: 'def456', house: 'Shanti' });

    expect(response.status).toBe(201);
    expect(response.body.house).toBe('Anand');
  });

  it('carries the officer code\'s branch into the activated session response', async () => {
    // Regression guard for ROADMAP.md Phase 0's branch wiring: a code
    // generated for AN must produce a session (and, downstream, votes) tagged
    // 'AN', not silently default to 'dwarka' just because the branch has to
    // pass through kioskService in between.
    const anCode: OfficerCode = {
      code: 'GHI789',
      officerName: 'Priya',
      electionType: 'school',
      branch: 'AN',
      createdAt: Date.now()
    };
    mockedDataStore.findOfficerCode.mockReturnValue(anCode);
    mockedDataStore.getPollState.mockReturnValue({
      activeElectionType: 'school',
      settings: { isOpen: true, allowRevote: false }
    });

    const { createApp } = await import('../app.js');
    const response = await request(createApp()).post('/api/kiosk/activate').send({ secret: 'ghi789' });

    expect(response.status).toBe(201);
    expect(response.body.branch).toBe('AN');
  });

  it('rejects a code that has not yet been allotted to a named polling officer', async () => {
    // A freshly generated code starts with officerName: '' (see
    // datastore.ts generateOfficerCodes) until an admin assigns it to a
    // real person via PUT /officer-codes/:code. Until then it must not be
    // usable to activate a ballot.
    const unallotedCode: OfficerCode = {
      code: 'JKL012',
      officerName: '',
      electionType: 'school',
      createdAt: Date.now()
    };
    mockedDataStore.findOfficerCode.mockReturnValue(unallotedCode);
    mockedDataStore.getPollState.mockReturnValue({
      activeElectionType: 'school',
      settings: { isOpen: true, allowRevote: false }
    });

    const { createApp } = await import('../app.js');
    const response = await request(createApp()).post('/api/kiosk/activate').send({ secret: 'jkl012' });

    expect(response.status).toBe(403);
    expect(response.body.error).toContain('not yet been allotted');
  });
});
